apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-config-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-aws-secret
      key: creds