apiVersion: do.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-do
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-do-secret
      key: token
